version: '3.8'

services:
  psql:
    build:
      context: ./psql
      dockerfile: Dockerfile
    volumes:
      - ~/transcendance/psql_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - internal_network
volumes:
  psql-data:


networks:
  internal_network:
    driver: bridge
